<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Z6UCrF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Z6UCrF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1Z6UCrF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1Z6UCrF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1Z6UCrF\App_KernelDevDebugContainer([
    'container.build_hash' => '1Z6UCrF',
    'container.build_id' => '3bc6e8f9',
    'container.build_time' => 1734448887,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Z6UCrF');
